################################################################################
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
################################################################################

[package]
description = "Zenoh Rust Transport library implementation of the Eclipse uProtocol"
edition = "2021"
include = [
    "/src/*",
    "/examples/*",
    "/Cargo.toml",
    "/README.md",
]
keywords = ["uProtocol", "SDK", "communication", "Zenoh"]
license = "Apache-2.0"
name = "up-transport-zenoh"
readme = "README.md"
repository = "https://github.com/eclipse-uprotocol/up-transport-zenoh-rust"
rust-version = "1.74.1"
version = "0.1.0"

[lints.clippy]
all = "deny"
pedantic = "deny"
#cargo = "deny"
#restriction = "deny"
#nursery = "deny"

[features]
default = []
benchmark-owned = ["up-rust/owned-frame-transport"]
zero-copy = ["zenoh/shared-memory", "zenoh/unstable"]

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1"
bitmask-enum = "2.2.4"
bytes = "1"
chrono = "0.4.31"
crossbeam-channel = "0.5.12"
lazy_static = "1.4.0"
prost = "0.12"
prost-types = "0.12"
protobuf = { version = "3.3" }
rand = "0.8.5"
tokio = { version = "1.45.1", default-features = false }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
up-rust = { git = "ssh://git@github.com/PLeVasseur/up-rust.git", rev = "26d70ef45af61fdd17d3e130845a5be155154b2e" }
zenoh = { version = "1.9.0", features = ["internal", "unstable"] }

[dev-dependencies]
serial_test = "3.2"
test-case = { version = "3.3" }
up-wire-xcdrv2 = { git = "ssh://git@github.com/PLeVasseur/up-wire-xcdrv2-rust.git", rev = "4092ba75e24f4f96b7088f37016c78ac75aa5c05" }

[[test]]
name = "zero_copy_transport"
required-features = ["zero-copy"]

[[test]]
name = "zenoh_owned_wire"
required-features = ["benchmark-owned"]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1

[package.metadata.docs.rs]
all-features = true
